name: Update Proxy List

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Debug - List files before
        run: ls -la

      - name: Run Parser Script
        run: python .github/workflows/parser.py
        continue-on-error: true   # продолжит даже если скрипт упадёт

      - name: Debug - List files after
        run: ls -la

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Автообновление прокси | $(date +'%Y-%m-%d %H:%M')"
          file_pattern: |
            YaltaVPN - Subscription
            log.csv
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
